name: Tim Mancuso Music
favicon: null
layout_spectrum: 0.96076
typography_spectrum: 0.43366
title: Musician Tim Mancuso - Steadfast
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#030305'
    - '#233774'
    - '#5f7fa8'
    - '#a6b6c6'
  brandStrength: 0.25
  lightness: 0.75
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
