name: Tim Mancuso Music
favicon: null
layout_spectrum: 0.7294672639109194
typography_spectrum: 0.3782077473588288
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.22504790569655597
  lightness: 0.5143351098522544
  saturation: 0.3957988265901804
  rhythmicContrast: 0.374562258599326
purpose: []
